#+TAGS: Think Explore Learn Read Test Develop Fix Blog Abandon

* TODO Experiments with Statistical Learning			    :Explore:

** TODO Chapter 18-21 (Part V) of AI a Modern Approach 		       :Read:

** TODO Monte Carlo Tree Search 				    :Develop:

A very simple outline for "learning" how to solve the 2x2x2 Rubik's cube.

1. Try (random?) move sequences of a fixed size (2 < x < 20) and store the sequence in a db
Each sequence should have an "analysis" of effects coupled with it (a diagram of start
and end state; including which pieces are affected and how).

2. Try solving a randomized cube (10 < y < 30 moves) using the db of sequences. Keep stats on
which sequences are used and prune the least useful ones every (1000 < z < 10000) solves.

2a. Since there are no "dead-ends" in the solution space we can use a distance metric and a
simple look-ahead (1 < w < 10) algorithm coupled with a rule saying that you're not allowed
to repeat a state/sequence pair twice to avoid loops in exploration.  


